CREATE TABLE webusers (
	username CHARACTER VARYING(250) NOT NULL, 
	password CHARACTER VARYING(250) NOT NULL, 
	ipaddress CHARACTER VARYING(250), 
	dtm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (username)
);
